#ebean:
#  dbSchema: splitbill  # use this schema rather than public
#  migration:
#
#    run: true       # run database migrations on startup
#
ebean:
  ddl:
    generate: true
#    migration: true
    run: false


datasource:
  db:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/splitbill
    driver: org.postgresql.Driver